// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRoot(arg1) {
  return window['go']['main']['App']['AddRoot'](arg1);
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function ListRoots() {
  return window['go']['main']['App']['ListRoots']();
}

export function RemoveRoot(arg1) {
  return window['go']['main']['App']['RemoveRoot'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetWallpaper(arg1, arg2) {
  return window['go']['main']['App']['SetWallpaper'](arg1, arg2);
}
