// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRoot(arg1:string):Promise<void>;

export function GetFiles():Promise<Array<main.ImageFile>>;

export function ListRoots():Promise<Array<main.Root>>;

export function RemoveRoot(arg1:string):Promise<void>;
